using System.Net; using System.Net.Http.Json; using System.Text.Json;
using IdentityTotpSelfServiceApi.Models; using Microsoft.AspNetCore.Identity; using Microsoft.Extensions.DependencyInjection; using Xunit;
using static IdentityTotpSelfServiceApi.Tests.TestUsers;
namespace IdentityTotpSelfServiceApi.Tests;
// 관리자 보안 강화(이관 문서 35장 우선순위 4): 관리자 API는 Admin 역할 + MFA로 로그인한 세션만 호출할 수 있다.
public sealed class AdminSecurityTests(ApiFactory f):IClassFixture<ApiFactory>
{
 async Task<(ApplicationUser Admin,string At)> MfaAdmin(HttpClient c){var a=await Create(f,"admin",admin:true);var key=await Enable2Fa(c,a.Email!);return(a,(await Login2Fa(c,a.Email!,key)).At());}
 static Task<HttpResponseMessage> Reset(HttpClient c,string at,string userId,string reason)=>c.SendAsync(Req(HttpMethod.Post,"/api/admin/users/2fa/reset",at,new{userId,reason}));

 // ADM-MFA: 비밀번호만으로 로그인한(amr=pwd) 관리자는 관리자 API를 쓸 수 없다.
 [Fact] public async Task PasswordOnlyAdmin_IsForbidden_AndDenialIsAudited(){var c=f.CreateClient();var a=await Create(f,"admin-pwd",admin:true);var t=await Create(f,"target");var at=(await Login(c,a.Email!)).At();Assert.Equal(HttpStatusCode.Forbidden,(await Reset(c,at,t.Id,"x")).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await c.SendAsync(Req(HttpMethod.Get,"/api/admin/audit-logs",at))).StatusCode);Assert.Contains(Audits(f,a.Id),z=>z.Type=="admin.denied"&&!z.Success&&z.Detail=="mfa-required");}
 [Fact] public async Task NonAdmin_DenialIsAuditedAsNotAdmin(){var c=f.CreateClient();var u=await Create(f,"plain");var at=(await Login(c,u.Email!)).At();Assert.Equal(HttpStatusCode.Forbidden,(await Reset(c,at,u.Id,"x")).StatusCode);Assert.Contains(Audits(f,u.Id),z=>z.Type=="admin.denied"&&z.Detail=="not-admin");}
 // 역할은 토큰 발급 시점에 담기므로, 역할을 회수하면 이미 발급된 관리자 토큰도 바로 거부되어야 한다.
 [Fact] public async Task AdminRoleRemoved_ExistingAdminTokenIsForbidden(){var c=f.CreateClient();var (a,at)=await MfaAdmin(c);var t=await Create(f,"target");using(var s=f.Services.CreateScope()){var um=s.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();Assert.True((await um.RemoveFromRoleAsync((await um.FindByIdAsync(a.Id))!,"Admin")).Succeeded);}Assert.Equal(HttpStatusCode.Forbidden,(await Reset(c,at,t.Id,"x")).StatusCode);}
 [Fact] public async Task MfaAdmin_Reset_RecordsActorAndReason(){var c=f.CreateClient();var (a,at)=await MfaAdmin(c);var t=await Create(f,"target");Assert.Equal(HttpStatusCode.NoContent,(await Reset(c,at,t.Id,"  lost device  ")).StatusCode);Assert.Contains(Audits(f,t.Id),z=>z.Type=="admin.2fa.reset"&&z.Success&&z.Actor==a.Id&&z.Detail=="lost device");}
 [Fact] public async Task Reset_ReasonTooLong_Returns400(){var c=f.CreateClient();var (_,at)=await MfaAdmin(c);var t=await Create(f,"target");Assert.Equal(HttpStatusCode.BadRequest,(await Reset(c,at,t.Id,new string('x',501))).StatusCode);Assert.Equal(HttpStatusCode.BadRequest,(await Reset(c,at,t.Id,"   ")).StatusCode);}
 // 관리자 API로 자기 2FA를 끄면 본인 확인(비밀번호+TOTP) 없이 보안 수준을 낮출 수 있다. self-service API를 쓰게 한다.
 [Fact] public async Task Reset_OwnAccount_Returns400(){var c=f.CreateClient();var (a,at)=await MfaAdmin(c);Assert.Equal(HttpStatusCode.BadRequest,(await Reset(c,at,a.Id,"self")).StatusCode);}
 [Fact] public async Task AuditLogQuery_FiltersByUser_AndIsItselfAudited(){var c=f.CreateClient();var (a,at)=await MfaAdmin(c);var t=await Create(f,"target");await Reset(c,at,t.Id,"query test");var r=await c.SendAsync(Req(HttpMethod.Get,$"/api/admin/audit-logs?userId={t.Id}&limit=10",at));Assert.Equal(HttpStatusCode.OK,r.StatusCode);var items=(await r.Content.ReadFromJsonAsync<JsonElement>()).EnumerateArray().ToArray();Assert.NotEmpty(items);Assert.All(items,z=>Assert.Equal(t.Id,z.GetProperty("userId").GetString()));Assert.Contains(items,z=>z.GetProperty("eventType").GetString()=="admin.2fa.reset"&&z.GetProperty("actorUserId").GetString()==a.Id);Assert.Contains(Audits(f,a.Id),z=>z.Type=="admin.audit.read"&&z.Actor==a.Id);Assert.Equal(HttpStatusCode.BadRequest,(await c.SendAsync(Req(HttpMethod.Get,"/api/admin/audit-logs?limit=501",at))).StatusCode);}
 [Fact] public async Task AdminRevokeAllSessions_KillsTargetTokens(){var c=f.CreateClient();var (a,at)=await MfaAdmin(c);var t=await Create(f,"target");var tl=await Login(c,t.Email!,"target-pc");var list=await c.SendAsync(Req(HttpMethod.Get,$"/api/admin/users/{t.Id}/sessions",at));Assert.Equal(HttpStatusCode.OK,list.StatusCode);Assert.Contains((await list.Content.ReadFromJsonAsync<JsonElement>()).EnumerateArray(),z=>z.GetProperty("deviceName").GetString()=="target-pc");Assert.Equal(HttpStatusCode.BadRequest,(await c.SendAsync(Req(HttpMethod.Post,"/api/admin/users/sessions/revoke-all",at,new{userId=t.Id,reason=""}))).StatusCode);Assert.Equal(HttpStatusCode.NoContent,(await c.SendAsync(Req(HttpMethod.Post,"/api/admin/users/sessions/revoke-all",at,new{userId=t.Id,reason="incident"}))).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await c.SendAsync(Req(HttpMethod.Get,"/api/account/me",tl.At()))).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=tl.Rt()})).StatusCode);Assert.Contains(Audits(f,t.Id),z=>z.Type=="admin.sessions.revoke-all"&&z.Actor==a.Id&&z.Detail=="incident");}
}
