using System.Net; using System.Net.Http.Headers; using System.Net.Http.Json; using System.Text.Json;
using IdentityTotpSelfServiceApi.Data; using IdentityTotpSelfServiceApi.Models; using Microsoft.AspNetCore.Identity; using Microsoft.Extensions.DependencyInjection; using Xunit;
namespace IdentityTotpSelfServiceApi.Tests;
public sealed class AuthFlowTests: IClassFixture<ApiFactory>
{
 readonly ApiFactory f; readonly HttpClient c; string currentEmail=""; public AuthFlowTests(ApiFactory f){this.f=f;c=f.CreateClient(new(){AllowAutoRedirect=false});}
 async Task<ApplicationUser> CreateUser(string? email=null,string pw="Strong!Pass123",bool confirmed=true){email ??= $"u-{Guid.NewGuid():N}@test.local"; currentEmail=email;using var s=f.Services.CreateScope();var um=s.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();var u=new ApplicationUser{UserName=email,Email=email,EmailConfirmed=confirmed};Assert.True((await um.CreateAsync(u,pw)).Succeeded);return u;}
 async Task<JsonElement> Login(string? email=null,string pw="Strong!Pass123"){email ??= currentEmail;var r=await c.PostAsJsonAsync("/api/auth/login",new{email,password=pw});Assert.Equal(HttpStatusCode.OK,r.StatusCode);return (await r.Content.ReadFromJsonAsync<JsonElement>());}
 [Fact] public async Task Register_SendsConfirmation_AndUnconfirmedCannotLogin(){var email=$"new-{Guid.NewGuid():N}@test.local";var r=await c.PostAsJsonAsync("/api/auth/register",new{email,password="Strong!Pass123"});Assert.Equal(HttpStatusCode.Created,r.StatusCode);Assert.Contains(f.Mail.Messages,x=>x.To==email);var l=await c.PostAsJsonAsync("/api/auth/login",new{email,password="Strong!Pass123"});Assert.Equal(HttpStatusCode.Unauthorized,l.StatusCode);}
 [Fact] public async Task Login_WrongPassword_Returns401(){var u=await CreateUser();var r=await c.PostAsJsonAsync("/api/auth/login",new{email=u.Email,password="wrong"});Assert.Equal(HttpStatusCode.Unauthorized,r.StatusCode);}
 [Fact] public async Task Login_FiveFailures_LocksAccount(){var u=await CreateUser();for(int i=0;i<5;i++)await c.PostAsJsonAsync("/api/auth/login",new{email=u.Email,password="wrong"});var r=await c.PostAsJsonAsync("/api/auth/login",new{email=u.Email,password="Strong!Pass123"});Assert.Equal((HttpStatusCode)423,r.StatusCode);}
 [Fact] public async Task Refresh_Rotates_AndReuseRevokesFamily(){await CreateUser();var l=await Login();var old=l.GetProperty("refreshToken").GetString()!;var r1=await c.PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=old});Assert.Equal(HttpStatusCode.OK,r1.StatusCode);var j=await r1.Content.ReadFromJsonAsync<JsonElement>();var next=j.GetProperty("refreshToken").GetString()!;var reuse=await c.PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=old});Assert.Equal(HttpStatusCode.Unauthorized,reuse.StatusCode);var family=await c.PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=next});Assert.Equal(HttpStatusCode.Unauthorized,family.StatusCode);}
 [Fact] public async Task Logout_Revoke_PreventsRefresh(){await CreateUser();var l=await Login();var rt=l.GetProperty("refreshToken").GetString()!;var x=await c.PostAsJsonAsync("/api/auth/token/revoke",new{refreshToken=rt});Assert.Equal(HttpStatusCode.NoContent,x.StatusCode);var r=await c.PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=rt});Assert.Equal(HttpStatusCode.Unauthorized,r.StatusCode);}
 [Fact] public async Task Totp_SetupEnableLogin_AndRecoveryCodeIsOneTime(){var u=await CreateUser();var l=await Login();var access=l.GetProperty("accessToken").GetString()!;c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",access);var setup=await c.PostAsync("/api/account/2fa/setup",null);var sj=await setup.Content.ReadFromJsonAsync<JsonElement>();var key=sj.GetProperty("sharedKey").GetString()!;var code=TotpHelper.Generate(key);var en=await c.PostAsJsonAsync("/api/account/2fa/enable",new{code});Assert.Equal(HttpStatusCode.OK,en.StatusCode);var ej=await en.Content.ReadFromJsonAsync<JsonElement>();var recovery=ej.GetProperty("recoveryCodes")[0].GetString()!;c.DefaultRequestHeaders.Authorization=null;var l2=await Login();Assert.True(l2.GetProperty("requiresTwoFactor").GetBoolean());var challenge=l2.GetProperty("challengeToken").GetString()!;var bad=await c.PostAsJsonAsync("/api/auth/2fa",new{challengeToken=challenge,code="000000"});Assert.Equal(HttpStatusCode.Unauthorized,bad.StatusCode);var ok=await c.PostAsJsonAsync("/api/auth/2fa",new{challengeToken=challenge,code=TotpHelper.Generate(key)});Assert.Equal(HttpStatusCode.OK,ok.StatusCode);var l3=await Login();var ch=l3.GetProperty("challengeToken").GetString()!;var rr=await c.PostAsJsonAsync("/api/auth/2fa/recovery",new{challengeToken=ch,recoveryCode=recovery});Assert.Equal(HttpStatusCode.OK,rr.StatusCode);var l4=await Login();var ch2=l4.GetProperty("challengeToken").GetString()!;var again=await c.PostAsJsonAsync("/api/auth/2fa/recovery",new{challengeToken=ch2,recoveryCode=recovery});Assert.Equal(HttpStatusCode.Unauthorized,again.StatusCode);}
 [Fact] public async Task SecurityStampChange_InvalidatesExistingAccessToken(){var u=await CreateUser();var l=await Login();var access=l.GetProperty("accessToken").GetString()!;using(var s=f.Services.CreateScope()){var um=s.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();var dbu=await um.FindByIdAsync(u.Id);await um.UpdateSecurityStampAsync(dbu!);}c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",access);var r=await c.GetAsync("/api/account/me");Assert.Equal(HttpStatusCode.Unauthorized,r.StatusCode);}
 [Fact] public async Task AdminEndpoint_RejectsNonAdmin(){await CreateUser();var l=await Login();c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",l.GetProperty("accessToken").GetString());var r=await c.PostAsJsonAsync("/api/admin/users/2fa/reset",new{userId="x",reason="test"});Assert.Equal(HttpStatusCode.Forbidden,r.StatusCode);}
}
