using System.Net; using System.Net.Http.Headers; using System.Net.Http.Json; using System.Text.Json;
using IdentityTotpSelfServiceApi.Data; using IdentityTotpSelfServiceApi.Models; using Microsoft.AspNetCore.Identity; using Microsoft.Extensions.DependencyInjection; using Xunit;
namespace IdentityTotpSelfServiceApi.Tests;
public sealed class RegressionTests:IClassFixture<ApiFactory>
{
 readonly ApiFactory f; public RegressionTests(ApiFactory f)=>this.f=f; static string E(string p)=>$"{p}-{Guid.NewGuid():N}@test.local";
 async Task<(ApplicationUser User,string Pw)> U(string p="reg",bool admin=false){var email=E(p);const string pw="Strong!Pass123";using var s=f.Services.CreateScope();var um=s.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();var u=new ApplicationUser{UserName=email,Email=email,EmailConfirmed=true};Assert.True((await um.CreateAsync(u,pw)).Succeeded);if(admin){var rm=s.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>();if(!await rm.RoleExistsAsync("Admin"))Assert.True((await rm.CreateAsync(new IdentityRole("Admin"))).Succeeded);Assert.True((await um.AddToRoleAsync(u,"Admin")).Succeeded);}return(u,pw);}
 static async Task<JsonElement> Login(HttpClient c,string email,string pw){var r=await c.PostAsJsonAsync("/api/auth/login",new{email,password=pw});Assert.Equal(HttpStatusCode.OK,r.StatusCode);return await r.Content.ReadFromJsonAsync<JsonElement>();}
 [Fact] public async Task PasswordChange_RevokesOldAccessAndRefresh_AndNewPasswordWorks(){var c=f.CreateClient();var x=await U("pwd");var l=await Login(c,x.User.Email!,x.Pw);var at=l.GetProperty("accessToken").GetString()!;var rt=l.GetProperty("refreshToken").GetString()!;c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",at);var ch=await c.PostAsJsonAsync("/api/account/change-password",new{currentPassword=x.Pw,newPassword="NewStrong!Pass456"});Assert.Equal(HttpStatusCode.NoContent,ch.StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await c.GetAsync("/api/account/me")).StatusCode);c.DefaultRequestHeaders.Authorization=null;Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=rt})).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/auth/login",new{email=x.User.Email,password=x.Pw})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await c.PostAsJsonAsync("/api/auth/login",new{email=x.User.Email,password="NewStrong!Pass456"})).StatusCode);}
 [Fact] public async Task AdminReset2Fa_Disables2Fa(){var target=await U("target");var admin=await U("admin",true);using(var s=f.Services.CreateScope()){var um=s.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();var t=await um.FindByIdAsync(target.User.Id);Assert.True((await um.SetTwoFactorEnabledAsync(t!,true)).Succeeded);}var c=f.CreateClient();/* 관리자 API는 MFA 세션만 허용한다(ADM-MFA) */var (akey,_)=await Enable2Fa(c,admin.User.Email!,admin.Pw);var al=await Login2Fa(c,admin.User.Email!,admin.Pw,akey);c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",al.GetProperty("accessToken").GetString());var r=await c.PostAsJsonAsync("/api/admin/users/2fa/reset",new{userId=target.User.Id,reason="lost device"});Assert.Equal(HttpStatusCode.NoContent,r.StatusCode);using var scope=f.Services.CreateScope();var um2=scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();Assert.False((await um2.FindByIdAsync(target.User.Id))!.TwoFactorEnabled);}
 [Fact] public async Task Refresh_SameTokenConcurrent_AtMostOneSucceeds(){var x=await U("race");var c=f.CreateClient();var l=await Login(c,x.User.Email!,x.Pw);var rt=l.GetProperty("refreshToken").GetString()!;var rs=await Task.WhenAll(f.CreateClient().PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=rt}),f.CreateClient().PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=rt}));Assert.True(rs.Count(z=>z.StatusCode==HttpStatusCode.OK)<=1,"동일 Refresh Token이 동시에 두 번 회전되었습니다.");}
 // REG-005: 2FA disable/reset 후에도 기존 Refresh Token으로 Access Token 재발급이 가능했던 문제
 static async Task<(string Key,string[] Recovery)> Enable2Fa(HttpClient c,string email,string pw){var l=await Login(c,email,pw);c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",l.GetProperty("accessToken").GetString());var sj=await (await c.PostAsync("/api/account/2fa/setup",null)).Content.ReadFromJsonAsync<JsonElement>();var key=sj.GetProperty("sharedKey").GetString()!;var en=await c.PostAsJsonAsync("/api/account/2fa/enable",new{code=TotpHelper.Generate(key)});Assert.Equal(HttpStatusCode.OK,en.StatusCode);var ej=await en.Content.ReadFromJsonAsync<JsonElement>();c.DefaultRequestHeaders.Authorization=null;return(key,ej.GetProperty("recoveryCodes").EnumerateArray().Select(z=>z.GetString()!).ToArray());}
 static async Task<string> Challenge(HttpClient c,string email,string pw){var l=await Login(c,email,pw);Assert.True(l.GetProperty("requiresTwoFactor").GetBoolean());return l.GetProperty("challengeToken").GetString()!;}
 static async Task<JsonElement> Login2Fa(HttpClient c,string email,string pw,string key){var r=await c.PostAsJsonAsync("/api/auth/2fa",new{challengeToken=await Challenge(c,email,pw),code=TotpHelper.Generate(key)});Assert.Equal(HttpStatusCode.OK,r.StatusCode);return await r.Content.ReadFromJsonAsync<JsonElement>();}
 static string WrongCode(string key)=>TotpHelper.Generate(key)=="000000"?"111111":"000000";
 [Theory,InlineData("/api/account/2fa/disable",HttpStatusCode.NoContent),InlineData("/api/account/2fa/reset",HttpStatusCode.OK)] public async Task TwoFactorDisableOrReset_RevokesExistingRefreshTokens(string path,HttpStatusCode expected){var x=await U("2fa-off");var c=f.CreateClient();var (key,_)=await Enable2Fa(c,x.User.Email!,x.Pw);var t=await Login2Fa(c,x.User.Email!,x.Pw,key);var rt=t.GetProperty("refreshToken").GetString()!;c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",t.GetProperty("accessToken").GetString());var r=await c.PostAsJsonAsync(path,new{password=x.Pw,code=TotpHelper.Generate(key)});Assert.Equal(expected,r.StatusCode);c.DefaultRequestHeaders.Authorization=null;Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=rt})).StatusCode);}
 // REG-008: 비밀번호만으로 받은 2FA challengeToken을 Bearer Access Token으로 써서 TOTP 없이 API를 호출할 수 있던 문제
 [Theory,InlineData("GET","/api/account/me"),InlineData("GET","/api/account/2fa/status"),InlineData("POST","/api/account/2fa/recovery-codes/regenerate")] public async Task ChallengeToken_IsNotAcceptedAsAccessToken(string method,string path){var x=await U("ch-bearer");var c=f.CreateClient();var (key,_)=await Enable2Fa(c,x.User.Email!,x.Pw);var ch=await Challenge(c,x.User.Email!,x.Pw);var req=new HttpRequestMessage(new HttpMethod(method),path);req.Headers.Authorization=new AuthenticationHeaderValue("Bearer",ch);if(method=="POST")req.Content=JsonContent.Create(new{code=TotpHelper.Generate(key)});Assert.Equal(HttpStatusCode.Unauthorized,(await c.SendAsync(req)).StatusCode);}
 // REG-007: 2FA 활성화 전 비밀번호만으로 받은 Refresh Token으로 amr=mfa Access Token을 받을 수 있던 문제
 [Fact] public async Task TwoFactorEnable_RevokesPasswordOnlyRefreshTokens(){var x=await U("2fa-on");var c=f.CreateClient();var rt=(await Login(c,x.User.Email!,x.Pw)).GetProperty("refreshToken").GetString()!;await Enable2Fa(c,x.User.Email!,x.Pw);Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=rt})).StatusCode);}
 // AUD: 로그인·2FA·로그아웃 보안 이벤트 감사 로그
 (string Type,bool Success,string? Detail)[] Audits(string userId){using var s=f.Services.CreateScope();var db=s.ServiceProvider.GetRequiredService<ApplicationDbContext>();return db.AuditLogs.Where(a=>a.UserId==userId).OrderBy(a=>a.Id).Select(a=>new{a.EventType,a.Success,a.Detail}).AsEnumerable().Select(a=>(a.EventType,a.Success,a.Detail)).ToArray();}
 [Fact] public async Task AuditLog_RecordsLoginTwoFactorRecoveryAndLogoutEvents(){var x=await U("audit");var c=f.CreateClient();var rt=(await Login(c,x.User.Email!,x.Pw)).GetProperty("refreshToken").GetString()!;Assert.Equal(HttpStatusCode.NoContent,(await c.PostAsJsonAsync("/api/auth/token/revoke",new{refreshToken=rt})).StatusCode);var (key,codes)=await Enable2Fa(c,x.User.Email!,x.Pw);var ch=await Challenge(c,x.User.Email!,x.Pw);Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/auth/2fa",new{challengeToken=ch,code=WrongCode(key)})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await c.PostAsJsonAsync("/api/auth/2fa",new{challengeToken=ch,code=TotpHelper.Generate(key)})).StatusCode);ch=await Challenge(c,x.User.Email!,x.Pw);Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/auth/2fa/recovery",new{challengeToken=ch,recoveryCode="wrong-code"})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await c.PostAsJsonAsync("/api/auth/2fa/recovery",new{challengeToken=ch,recoveryCode=codes[0]})).StatusCode);var t=await Login2Fa(c,x.User.Email!,x.Pw,key);c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",t.GetProperty("accessToken").GetString());Assert.Equal(HttpStatusCode.NoContent,(await c.PostAsJsonAsync("/api/account/2fa/disable",new{password=x.Pw,code=TotpHelper.Generate(key)})).StatusCode);
  var a=Audits(x.User.Id);var types=a.Select(z=>z.Type).ToArray();foreach(var e in new[]{"login.success","logout","2fa.setup","2fa.enable","login.2fa-required","2fa.success","recovery.success","2fa.disable"})Assert.Contains(e,types);Assert.Contains(a,z=>z.Type=="2fa.failed"&&!z.Success);Assert.Contains(a,z=>z.Type=="recovery.failed"&&!z.Success);
  // 감사 로그에 토큰·복구 코드·TOTP Secret 원문이 남으면 안 된다.
  foreach(var z in a)foreach(var secret in new[]{rt,key,codes[0]})Assert.DoesNotContain(secret,z.Detail??"");}
 [Fact] public async Task AuditLog_RecordsTwoFactorResetAndRecoveryCodeRegeneration(){var x=await U("audit-reset");var c=f.CreateClient();var (key,_)=await Enable2Fa(c,x.User.Email!,x.Pw);var t=await Login2Fa(c,x.User.Email!,x.Pw,key);c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",t.GetProperty("accessToken").GetString());Assert.Equal(HttpStatusCode.OK,(await c.PostAsJsonAsync("/api/account/2fa/recovery-codes/regenerate",new{code=TotpHelper.Generate(key)})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await c.PostAsJsonAsync("/api/account/2fa/reset",new{password=x.Pw,code=TotpHelper.Generate(key)})).StatusCode);var types=Audits(x.User.Id).Select(z=>z.Type).ToArray();Assert.Contains("2fa.recovery-codes.regenerate",types);Assert.Contains("2fa.reset",types);}
 [Fact] public async Task AuditLog_RecordsAccountLockedOnceAndLockedRejections(){var x=await U("audit-lock");var c=f.CreateClient();var (key,_)=await Enable2Fa(c,x.User.Email!,x.Pw);var ch=await Challenge(c,x.User.Email!,x.Pw);for(int i=0;i<5;i++)await c.PostAsJsonAsync("/api/auth/2fa",new{challengeToken=ch,code=WrongCode(key)});Assert.Equal((HttpStatusCode)423,(await c.PostAsJsonAsync("/api/auth/2fa",new{challengeToken=ch,code=TotpHelper.Generate(key)})).StatusCode);Assert.Equal((HttpStatusCode)423,(await c.PostAsJsonAsync("/api/auth/login",new{email=x.User.Email,password=x.Pw})).StatusCode);var types=Audits(x.User.Id).Select(z=>z.Type).ToArray();Assert.Equal(1,types.Count(z=>z=="account.locked"));Assert.Contains("2fa.locked",types);Assert.Contains("login.locked",types);}
 [Fact] public async Task AuditLog_RefreshReuse_RecordsTokenOwner(){var x=await U("audit-reuse");var c=f.CreateClient();var old=(await Login(c,x.User.Email!,x.Pw)).GetProperty("refreshToken").GetString()!;Assert.Equal(HttpStatusCode.OK,(await c.PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=old})).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=old})).StatusCode);Assert.Contains(Audits(x.User.Id),z=>z.Type=="refresh.reuse"&&!z.Success);}
 // REG-010: 로그아웃·비밀번호 변경 등으로 정상 폐기된 토큰도 refresh.reuse(탈취 의심)로 기록되어 경보가 과다하던 문제
 [Fact] public async Task AuditLog_RefreshWithLoggedOutToken_IsRevokedNotReuse(){var x=await U("audit-logout");var c=f.CreateClient();var rt=(await Login(c,x.User.Email!,x.Pw)).GetProperty("refreshToken").GetString()!;Assert.Equal(HttpStatusCode.NoContent,(await c.PostAsJsonAsync("/api/auth/token/revoke",new{refreshToken=rt})).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=rt})).StatusCode);var a=Audits(x.User.Id);Assert.DoesNotContain(a,z=>z.Type=="refresh.reuse");Assert.Contains(a,z=>z.Type=="refresh.revoked"&&!z.Success&&z.Detail=="user-revoke");}
 [Fact] public async Task AuditLog_RefreshAfterPasswordChange_IsRevokedNotReuse(){var x=await U("audit-pwchg");var c=f.CreateClient();var l=await Login(c,x.User.Email!,x.Pw);var rt=l.GetProperty("refreshToken").GetString()!;c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",l.GetProperty("accessToken").GetString());Assert.Equal(HttpStatusCode.NoContent,(await c.PostAsJsonAsync("/api/account/change-password",new{currentPassword=x.Pw,newPassword="NewStrong!Pass456"})).StatusCode);c.DefaultRequestHeaders.Authorization=null;Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=rt})).StatusCode);var a=Audits(x.User.Id);Assert.DoesNotContain(a,z=>z.Type=="refresh.reuse");Assert.Contains(a,z=>z.Type=="refresh.revoked"&&z.Detail=="password-change");}
 // REG-012: User-Agent가 AuditLogs.UserAgent(512자)보다 길면 SQL Server에서 감사 로그 저장이 실패해 로그인이 500이 되던 문제
 [Fact] public async Task Login_WithVeryLongUserAgent_Succeeds(){var x=await U("long-ua");var c=f.CreateClient();c.DefaultRequestHeaders.TryAddWithoutValidation("User-Agent","Mozilla/5.0 "+new string('x',1000));var l=await Login(c,x.User.Email!,x.Pw);Assert.False(string.IsNullOrEmpty(l.GetProperty("accessToken").GetString()));}
 // REG-014: 복구 코드를 공백으로 보내면 Identity가 ArgumentException을 던져 500이 되던 문제(VB6 화면에서 빈 칸으로 [복구 코드 로그인]).
 // 빈 값은 400으로 거절하고 잠금 실패 횟수에는 넣지 않는다. TOTP 코드도 공백이면 500이 아니어야 한다.
 [Theory,InlineData("/api/auth/2fa/recovery"),InlineData("/api/auth/2fa")] public async Task SecondFactor_BlankCode_IsRejectedWithoutServerError(string path){var x=await U("blank-code");var c=f.CreateClient();await Enable2Fa(c,x.User.Email!,x.Pw);var ch=await Challenge(c,x.User.Email!,x.Pw);var r=await c.PostAsJsonAsync(path,new{challengeToken=ch,recoveryCode="   ",code="   "});Assert.Equal(HttpStatusCode.BadRequest,r.StatusCode);using var s=f.Services.CreateScope();Assert.Equal(0,(await s.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>().FindByIdAsync(x.User.Id))!.AccessFailedCount);}
 // REG-006: TOTP/복구 코드 2차 인증 실패가 누적되어도 계정 잠금이 적용되지 않던 문제
 [Fact] public async Task TotpFailures_LockAccount_AndCorrectCodeIsRejectedWith423(){var x=await U("totp-lock");var c=f.CreateClient();var (key,_)=await Enable2Fa(c,x.User.Email!,x.Pw);var ch=await Challenge(c,x.User.Email!,x.Pw);for(int i=0;i<5;i++)Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/auth/2fa",new{challengeToken=ch,code=WrongCode(key)})).StatusCode);Assert.Equal((HttpStatusCode)423,(await c.PostAsJsonAsync("/api/auth/2fa",new{challengeToken=ch,code=TotpHelper.Generate(key)})).StatusCode);}
 [Fact] public async Task RecoveryCodeFailures_LockAccount_AndValidCodeIsRejectedWith423(){var x=await U("rc-lock");var c=f.CreateClient();var (_,codes)=await Enable2Fa(c,x.User.Email!,x.Pw);var ch=await Challenge(c,x.User.Email!,x.Pw);for(int i=0;i<5;i++)Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/auth/2fa/recovery",new{challengeToken=ch,recoveryCode="wrong-code"})).StatusCode);Assert.Equal((HttpStatusCode)423,(await c.PostAsJsonAsync("/api/auth/2fa/recovery",new{challengeToken=ch,recoveryCode=codes[0]})).StatusCode);}
}
public sealed class RateLimitTests:IClassFixture<LowRateLimitApiFactory>{readonly LowRateLimitApiFactory f;public RateLimitTests(LowRateLimitApiFactory f)=>this.f=f;[Fact]public async Task AuthPolicy_ThirdRequestWithinWindow_Returns429(){var c=f.CreateClient();var a=await c.PostAsJsonAsync("/api/auth/login",new{email="none@test.local",password="x"});var b=await c.PostAsJsonAsync("/api/auth/login",new{email="none@test.local",password="x"});var d=await c.PostAsJsonAsync("/api/auth/login",new{email="none@test.local",password="x"});Assert.Equal(HttpStatusCode.Unauthorized,a.StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,b.StatusCode);Assert.Equal((HttpStatusCode)429,d.StatusCode);}}
