using System.Net; using System.Net.Http.Headers; using System.Net.Http.Json; using System.Text.Json;
using IdentityTotpSelfServiceApi.Models; using Microsoft.AspNetCore.Identity; using Microsoft.Extensions.DependencyInjection; using Xunit;
namespace IdentityTotpSelfServiceApi.Tests;
public sealed class RegressionTests:IClassFixture<ApiFactory>
{
 readonly ApiFactory f; public RegressionTests(ApiFactory f)=>this.f=f; static string E(string p)=>$"{p}-{Guid.NewGuid():N}@test.local";
 async Task<(ApplicationUser User,string Pw)> U(string p="reg",bool admin=false){var email=E(p);const string pw="Strong!Pass123";using var s=f.Services.CreateScope();var um=s.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();var u=new ApplicationUser{UserName=email,Email=email,EmailConfirmed=true};Assert.True((await um.CreateAsync(u,pw)).Succeeded);if(admin){var rm=s.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>();if(!await rm.RoleExistsAsync("Admin"))Assert.True((await rm.CreateAsync(new IdentityRole("Admin"))).Succeeded);Assert.True((await um.AddToRoleAsync(u,"Admin")).Succeeded);}return(u,pw);}
 static async Task<JsonElement> Login(HttpClient c,string email,string pw){var r=await c.PostAsJsonAsync("/api/auth/login",new{email,password=pw});Assert.Equal(HttpStatusCode.OK,r.StatusCode);return await r.Content.ReadFromJsonAsync<JsonElement>();}
 [Fact] public async Task PasswordChange_RevokesOldAccessAndRefresh_AndNewPasswordWorks(){var c=f.CreateClient();var x=await U("pwd");var l=await Login(c,x.User.Email!,x.Pw);var at=l.GetProperty("accessToken").GetString()!;var rt=l.GetProperty("refreshToken").GetString()!;c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",at);var ch=await c.PostAsJsonAsync("/api/account/change-password",new{currentPassword=x.Pw,newPassword="NewStrong!Pass456"});Assert.Equal(HttpStatusCode.NoContent,ch.StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await c.GetAsync("/api/account/me")).StatusCode);c.DefaultRequestHeaders.Authorization=null;Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=rt})).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/auth/login",new{email=x.User.Email,password=x.Pw})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await c.PostAsJsonAsync("/api/auth/login",new{email=x.User.Email,password="NewStrong!Pass456"})).StatusCode);}
 [Fact] public async Task AdminReset2Fa_Disables2Fa(){var target=await U("target");var admin=await U("admin",true);using(var s=f.Services.CreateScope()){var um=s.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();var t=await um.FindByIdAsync(target.User.Id);Assert.True((await um.SetTwoFactorEnabledAsync(t!,true)).Succeeded);}var c=f.CreateClient();var al=await Login(c,admin.User.Email!,admin.Pw);c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",al.GetProperty("accessToken").GetString());var r=await c.PostAsJsonAsync("/api/admin/users/2fa/reset",new{userId=target.User.Id,reason="lost device"});Assert.Equal(HttpStatusCode.NoContent,r.StatusCode);using var scope=f.Services.CreateScope();var um2=scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();Assert.False((await um2.FindByIdAsync(target.User.Id))!.TwoFactorEnabled);}
 [Fact] public async Task Refresh_SameTokenConcurrent_AtMostOneSucceeds(){var x=await U("race");var c=f.CreateClient();var l=await Login(c,x.User.Email!,x.Pw);var rt=l.GetProperty("refreshToken").GetString()!;var rs=await Task.WhenAll(f.CreateClient().PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=rt}),f.CreateClient().PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=rt}));Assert.True(rs.Count(z=>z.StatusCode==HttpStatusCode.OK)<=1,"동일 Refresh Token이 동시에 두 번 회전되었습니다.");}
}
public sealed class RateLimitTests:IClassFixture<LowRateLimitApiFactory>{readonly LowRateLimitApiFactory f;public RateLimitTests(LowRateLimitApiFactory f)=>this.f=f;[Fact]public async Task AuthPolicy_ThirdRequestWithinWindow_Returns429(){var c=f.CreateClient();var a=await c.PostAsJsonAsync("/api/auth/login",new{email="none@test.local",password="x"});var b=await c.PostAsJsonAsync("/api/auth/login",new{email="none@test.local",password="x"});var d=await c.PostAsJsonAsync("/api/auth/login",new{email="none@test.local",password="x"});Assert.Equal(HttpStatusCode.Unauthorized,a.StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,b.StatusCode);Assert.Equal((HttpStatusCode)429,d.StatusCode);}}
