using System.Net; using System.Net.Http.Json; using System.Text.Json;
using IdentityTotpSelfServiceApi.Data; using IdentityTotpSelfServiceApi.Entities; using IdentityTotpSelfServiceApi.Services; using Microsoft.EntityFrameworkCore; using Microsoft.Extensions.DependencyInjection; using Xunit;
using static IdentityTotpSelfServiceApi.Tests.TestUsers;
namespace IdentityTotpSelfServiceApi.Tests;
// 세션(기기) 관리(이관 문서 35장 우선순위 5). 세션 = Refresh Token family. Access Token의 sid 클레임이 세션을 가리킨다.
public sealed class SessionTests(ApiFactory f):IClassFixture<ApiFactory>
{
 static async Task<JsonElement[]> Sessions(HttpClient c,string at){var r=await c.SendAsync(Req(HttpMethod.Get,"/api/account/sessions",at));Assert.Equal(HttpStatusCode.OK,r.StatusCode);return (await r.Content.ReadFromJsonAsync<JsonElement>()).EnumerateArray().ToArray();}
 static Task<HttpResponseMessage> Refresh(HttpClient c,string rt)=>c.PostAsJsonAsync("/api/auth/token/refresh",new{refreshToken=rt});
 static Task<HttpResponseMessage> Me(HttpClient c,string at)=>c.SendAsync(Req(HttpMethod.Get,"/api/account/me",at));

 [Fact] public async Task Sessions_ListsDevices_MarksCurrent_AndSurvivesRotation(){var c=f.CreateClient();var u=await Create(f,"sess");var pc=await Login(c,u.Email!,"Office PC");var phone=await Login(c,u.Email!,"Phone");var rot=await (await Refresh(c,phone.Rt())).Content.ReadFromJsonAsync<JsonElement>();var list=await Sessions(c,pc.At());Assert.Equal(2,list.Length);Assert.Single(list,z=>z.GetProperty("current").GetBoolean()&&z.GetProperty("deviceName").GetString()=="Office PC");var p=Assert.Single(list,z=>z.GetProperty("deviceName").GetString()=="Phone");Assert.True(p.GetProperty("lastActiveAt").GetDateTimeOffset()>=p.GetProperty("createdAt").GetDateTimeOffset());Assert.True((await Sessions(c,rot.At())).Single(z=>z.GetProperty("current").GetBoolean()).GetProperty("deviceName").GetString()=="Phone");}
 // 응답에 토큰 원문이나 해시가 나가면 안 된다.
 [Fact] public async Task Sessions_DoNotExposeTokens(){var c=f.CreateClient();var u=await Create(f,"sess-leak");var l=await Login(c,u.Email!,"pc");var r=await c.SendAsync(Req(HttpMethod.Get,"/api/account/sessions",l.At()));var body=await r.Content.ReadAsStringAsync();Assert.DoesNotContain(l.Rt(),body);Assert.DoesNotContain(RefreshTokenService.Hash(l.Rt()),body);Assert.DoesNotContain("tokenHash",body,StringComparison.OrdinalIgnoreCase);}
 // 특정 기기 강제 로그아웃: 그 기기의 Refresh와 Access Token이 즉시 무효가 되고 다른 기기는 유지된다.
 [Fact] public async Task RevokeSession_KillsThatDeviceImmediately_OnlyThatDevice(){var c=f.CreateClient();var u=await Create(f,"sess-one");var pc=await Login(c,u.Email!,"pc");var lost=await Login(c,u.Email!,"lost phone");var sid=(await Sessions(c,pc.At())).Single(z=>z.GetProperty("deviceName").GetString()=="lost phone").GetProperty("sessionId").GetString()!;Assert.Equal(HttpStatusCode.NoContent,(await c.SendAsync(Req(HttpMethod.Delete,$"/api/account/sessions/{sid}",pc.At()))).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await Me(c,lost.At())).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await Refresh(c,lost.Rt())).StatusCode);Assert.Equal(HttpStatusCode.OK,(await Me(c,pc.At())).StatusCode);Assert.Equal(HttpStatusCode.OK,(await Refresh(c,pc.Rt())).StatusCode);var a=Audits(f,u.Id);Assert.Contains(a,z=>z.Type=="session.revoke"&&z.Success);Assert.Contains(a,z=>z.Type=="refresh.revoked"&&z.Detail=="session-revoke");Assert.DoesNotContain(a,z=>z.Type=="refresh.reuse");}
 // 다른 사용자의 세션 ID로는 폐기할 수 없다(존재 여부도 구분하지 않고 404).
 [Fact] public async Task RevokeSession_OtherUsersSession_Returns404(){var c=f.CreateClient();var a=await Create(f,"sess-a");var b=await Create(f,"sess-b");var al=await Login(c,a.Email!,"a");var bl=await Login(c,b.Email!,"b");var bsid=(await Sessions(c,bl.At())).Single().GetProperty("sessionId").GetString()!;Assert.Equal(HttpStatusCode.NotFound,(await c.SendAsync(Req(HttpMethod.Delete,$"/api/account/sessions/{bsid}",al.At()))).StatusCode);Assert.Equal(HttpStatusCode.OK,(await Me(c,bl.At())).StatusCode);Assert.Equal(HttpStatusCode.NotFound,(await c.SendAsync(Req(HttpMethod.Delete,"/api/account/sessions/nope",al.At()))).StatusCode);}
 [Fact] public async Task RevokeOthers_KeepsCurrentSessionOnly(){var c=f.CreateClient();var u=await Create(f,"sess-others");var keep=await Login(c,u.Email!,"keep");var o1=await Login(c,u.Email!,"o1");var o2=await Login(c,u.Email!,"o2");var r=await c.SendAsync(Req(HttpMethod.Post,"/api/account/sessions/revoke-others",keep.At()));Assert.Equal(HttpStatusCode.OK,r.StatusCode);Assert.Equal(2,(await r.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("revokedSessions").GetInt32());foreach(var o in new[]{o1,o2}){Assert.Equal(HttpStatusCode.Unauthorized,(await Me(c,o.At())).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await Refresh(c,o.Rt())).StatusCode);}Assert.Single(await Sessions(c,keep.At()));Assert.Equal(HttpStatusCode.OK,(await Refresh(c,keep.Rt())).StatusCode);}
 // 전체 기기 로그아웃: 현재 기기를 포함해 모든 Access/Refresh가 무효(SecurityStamp 갱신 + 전체 폐기).
 [Fact] public async Task RevokeAll_KillsEverySessionIncludingCurrent(){var c=f.CreateClient();var u=await Create(f,"sess-all");var a=await Login(c,u.Email!,"a");var b=await Login(c,u.Email!,"b");Assert.Equal(HttpStatusCode.NoContent,(await c.SendAsync(Req(HttpMethod.Post,"/api/account/sessions/revoke-all",a.At()))).StatusCode);foreach(var x in new[]{a,b}){Assert.Equal(HttpStatusCode.Unauthorized,(await Me(c,x.At())).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await Refresh(c,x.Rt())).StatusCode);}Assert.Contains(Audits(f,u.Id),z=>z.Type=="session.revoke-all");Assert.Equal(HttpStatusCode.OK,(await Me(c,(await Login(c,u.Email!)).At())).StatusCode);}
 // 로그아웃(revoke)한 세션의 Access Token도 만료를 기다리지 않고 거부된다.
 [Fact] public async Task Logout_AlsoInvalidatesThatSessionsAccessToken(){var c=f.CreateClient();var u=await Create(f,"sess-logout");var l=await Login(c,u.Email!);Assert.Equal(HttpStatusCode.OK,(await Me(c,l.At())).StatusCode);Assert.Equal(HttpStatusCode.NoContent,(await c.PostAsJsonAsync("/api/auth/token/revoke",new{refreshToken=l.Rt()})).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await Me(c,l.At())).StatusCode);}
 // 재사용 탐지로 family가 폐기되면 그 세션의 Access Token도 즉시 거부된다.
 [Fact] public async Task ReuseDetection_AlsoInvalidatesSessionAccessToken(){var c=f.CreateClient();var u=await Create(f,"sess-reuse");var l=await Login(c,u.Email!);var n=await (await Refresh(c,l.Rt())).Content.ReadFromJsonAsync<JsonElement>();Assert.Equal(HttpStatusCode.Unauthorized,(await Refresh(c,l.Rt())).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await Me(c,n.At())).StatusCode);}
 [Fact] public async Task DeviceName_IsKeptThrough2FaLogin_AndTruncated(){var c=f.CreateClient();var u=await Create(f,"sess-2fa");var key=await Enable2Fa(c,u.Email!);var t=await Login2Fa(c,u.Email!,key,new string('d',300));var s=Assert.Single(await Sessions(c,t.At()));Assert.Equal(128,s.GetProperty("deviceName").GetString()!.Length);}

 // 만료 토큰 정리: 보존 기간이 지난 만료 토큰만 지우고, 활성 토큰과 보존 기간 내 토큰(재사용 탐지에 필요)은 남긴다.
 [Fact] public async Task Purge_DeletesOnlyTokensExpiredBeyondRetention(){var u=await Create(f,"purge");var now=DateTimeOffset.UtcNow;using var s=f.Services.CreateScope();var db=s.ServiceProvider.GetRequiredService<ApplicationDbContext>();RefreshToken T(string tag,DateTimeOffset exp,bool revoked)=>new(){UserId=u.Id,TokenHash=RefreshTokenService.Hash(tag+Guid.NewGuid()),FamilyId=Guid.NewGuid().ToString("N"),CreatedAt=exp.AddDays(-14),ExpiresAt=exp,RevokedAt=revoked?exp.AddDays(-1):null,RevokeReason=revoked?"rotated":null};var old=T("old",now.AddDays(-40),false);var oldRevoked=T("oldrev",now.AddDays(-31),true);var recent=T("recent",now.AddDays(-2),true);var active=T("active",now.AddDays(5),false);db.RefreshTokens.AddRange(old,oldRevoked,recent,active);await db.SaveChangesAsync();var svc=s.ServiceProvider.GetRequiredService<RefreshTokenService>();var n=await svc.PurgeExpiredAsync(now.AddDays(-30),batchSize:1);Assert.True(n>=2);db.ChangeTracker.Clear();var left=await db.RefreshTokens.Where(x=>x.UserId==u.Id).Select(x=>x.Id).ToListAsync();Assert.DoesNotContain(old.Id,left);Assert.DoesNotContain(oldRevoked.Id,left);Assert.Contains(recent.Id,left);Assert.Contains(active.Id,left);}
 // 살아 있는 세션(family)의 오래된 회전 토큰은 지우지 않는다. 지우면 그 토큰이 다시 들어왔을 때 재사용 탐지(family 폐기)가 동작하지 않는다.
 [Fact] public async Task Purge_KeepsOldRotatedTokenOfLiveFamily_SoReuseIsStillDetected(){var u=await Create(f,"purge-live");var now=DateTimeOffset.UtcNow;var fam=Guid.NewGuid().ToString("N");var oldRaw="old-"+Guid.NewGuid();var activeRaw="act-"+Guid.NewGuid();using(var s=f.Services.CreateScope()){var db=s.ServiceProvider.GetRequiredService<ApplicationDbContext>();db.RefreshTokens.AddRange(new RefreshToken{UserId=u.Id,TokenHash=RefreshTokenService.Hash(oldRaw),FamilyId=fam,CreatedAt=now.AddDays(-80),ExpiresAt=now.AddDays(-40),RevokedAt=now.AddDays(-79),RevokeReason="rotated"},new RefreshToken{UserId=u.Id,TokenHash=RefreshTokenService.Hash(activeRaw),FamilyId=fam,CreatedAt=now.AddDays(-1),ExpiresAt=now.AddDays(13)});await db.SaveChangesAsync();await s.ServiceProvider.GetRequiredService<RefreshTokenService>().PurgeExpiredAsync(now.AddDays(-30));}var c=f.CreateClient();Assert.Equal(HttpStatusCode.Unauthorized,(await Refresh(c,oldRaw)).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await Refresh(c,activeRaw)).StatusCode);Assert.Contains(Audits(f,u.Id),z=>z.Type=="refresh.reuse");}
 // 정리 작업이 호스트에 등록되어 있고, 한 번 실행하면 보존 기간이 지난 만료 토큰을 지운다.
 [Fact] public async Task CleanupService_IsRegistered_AndRunOncePurges(){var u=await Create(f,"purge-svc");using(var s=f.Services.CreateScope()){var db=s.ServiceProvider.GetRequiredService<ApplicationDbContext>();db.RefreshTokens.Add(new RefreshToken{UserId=u.Id,TokenHash=RefreshTokenService.Hash(Guid.NewGuid().ToString()),FamilyId=Guid.NewGuid().ToString("N"),CreatedAt=DateTimeOffset.UtcNow.AddDays(-60),ExpiresAt=DateTimeOffset.UtcNow.AddDays(-45)});await db.SaveChangesAsync();}var svc=f.Services.GetServices<Microsoft.Extensions.Hosting.IHostedService>().OfType<RefreshTokenCleanupService>().Single();Assert.True(await svc.RunOnceAsync()>=1);using var s2=f.Services.CreateScope();Assert.False(await s2.ServiceProvider.GetRequiredService<ApplicationDbContext>().RefreshTokens.AnyAsync(x=>x.UserId==u.Id));}
}
